_G.ABOUT = LOC "$$$/shamurai/textr/about=About"
_G.ABOUT_TEXT = LOC "$$$/shamurai/textr/about=Recognize text in photos using the Google Cloud Vision API and add a searchable field for the photos. This came about as I was listening to the PetaPixel Podcast #57 and someone had a question about an automated way to tag race bib numbers in Lightroom. I thought it shouldn't be that hard to whip up in today's age...and here we are."
_G.ADD = LOC "$$$/shamurai/textr/add=Add OCR Tags"
_G.ADDING = LOC "$$$/shamurai/textr/adding=Adding OCR Tags"
_G.ALLOW_REGEX = LOC "$$$/shamurai/textr/aregex=Find Regex"
_G.API_KEY_EMPTY = LOC "$$$/shamurai/textr/apikeyempty=API Key is empty! Configure it in the Plug-in Manager."
_G.API_KEY_TITLE = LOC "$$$/shamurai/textr/apikeytitle=API Key (CLI)"
_G.API_TIP = LOC "$$$/shamurai/textr/apitip=Should be a long API key of random letters and numbers."
_G.BATCHSIZE = LOC "$$$/shamurai/textr/batchsize=Maximum Batch Size"
_G.BY_LABEL = LOC "$$$/shamurai/textr/bylabel=By"
_G.CALL_CLOUD = LOC "$$$/shamurai/textr/call=Calling Google Cloud"
_G.COMBO_TIP = LOC "$$$/shamurai/textr/ctip=Numbers & Letters: ^[a-zA-Z0-9]+$\nNumbers: ^[0-9]+$\nLetters: ^[a-zA-Z]+$"
_G.CONF = LOC "$$$/shamurai/textr/conf=Configuration"
_G.DECODE = LOC "$$$/shamurai/textr/decode=Decoding JSON" 
_G.DONATE_BUTTON = LOC "$$$/shamurai/textr/donateb=Donate: First Exposures"
_G.DONATE_LABEL = LOC "$$$/shamurai/textr/donatel=Donate"
_G.DONATE_TEXT = LOC "$$$/shamurai/textr/donatetext=If you like this plugin or use it for work, please make a donation to First Exposures. It's a San Francisco-based, nationally recognized youth mentoring program that strives to make a major long-term difference in the lives of high-need, underserved San Francisco Bay Area youth by providing a venue for them to enhance their self-confidence, develop their creativity, and gain a passion for learning."
_G.DONATE_URL = "https://www.firstexposures.org/"
_G.ENDPOINT_URL = "https://vision.googleapis.com/v1/images:annotate"
_G.EXCEEDS = LOC "$$$/shamurai/textr/exceeds= %d photos is the max."
_G.FETCHING = LOC "$$$/shamurai/textr/fetch=Fetching Catalog"
_G.FOUND_TEXT = LOC "$$$/shamurai/textr/foundtext=Found Text"
_G.GCONF = LOC "$$$/shamurai/textr/gconf=<Please Configure In Google Clound Dashboard>"
_G.GDASH = LOC "$$$/shamurai/textr/gdash=Google Cloud Dashboard"
_G.GEN_HASHES = LOC "$$$/shamurai/textr/hash=Generating Hashes"
_G.GIT_BUTTON = LOC "$$$/shamurai/textr/gitdash=Github: Textr"
_G.GIT_URL = "https://github.com/ayman/textr"
_G.LICENSE_LABEL = LOC "$$$/shamurai/textr/license=License"
_G.MATCHED_LENGTH = LOC "$$$/shamurai/textr/tlength=Matched length"
_G.MIT_LICENSE = "MIT License\n\nCopyright (c) 2017 David A. Shamma\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE."
_G.OCR = LOC "$$$/shamurai/textr/ocr=OCR"
_G.PLUGIN_NAME = LOC "$$$/shamurai/textr/pluginName=Textr OCR Tagger"
_G.SETTINGS = LOC "$$$/shamurai/textr/settings=Settings"
_G.SUPPORT = LOC "$$$/shamurai/textr/support=Generally unsupported.  You can file issues on the Github page but you can also fix them and submit a pull request."
_G.SUPPORT_LABEL = LOC "$$$/shamurai/textr/supportlabel=Support"
_G.THUMBSIZE = LOC "$$$/shamurai/textr/thumbsize=Thumb size"
_G.TOOMANY = LOC "$$$/shamurai/textr/toomany=Too Many (%d photos)."
_G.URL = "https://console.cloud.google.com"

